# Generated by Django 3.0.7 on 2020-07-03 17:59

import django.db.models.deletion
import djangoyearlessdate.models
from django.db import migrations, models

import plants.models
import plants.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Main name, must be unique", unique=True
                    ),
                ),
                (
                    "name_alt",
                    models.TextField(
                        blank=True,
                        help_text="Alternative name, i.e. in latin or other common names",
                        null=True,
                    ),
                ),
                (
                    "name_en",
                    models.TextField(
                        blank=True, help_text="Name in English", null=True
                    ),
                ),
                ("when", models.TextField(blank=True, null=True)),
                (
                    "bloom_start",
                    djangoyearlessdate.models.YearlessDateField(
                        blank=True, max_length=4, null=True
                    ),
                ),
                (
                    "bloom_end",
                    djangoyearlessdate.models.YearlessDateField(
                        blank=True, max_length=4, null=True
                    ),
                ),
                (
                    "collect_start",
                    djangoyearlessdate.models.YearlessDateField(
                        blank=True, max_length=4, null=True
                    ),
                ),
                (
                    "collect_end",
                    djangoyearlessdate.models.YearlessDateField(
                        blank=True, max_length=4, null=True
                    ),
                ),
                ("where", models.TextField(blank=True, null=True)),
                ("how", models.TextField(blank=True, null=True)),
                ("benefit", models.TextField(blank=True, null=True)),
                ("harm", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("history", models.TextField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=plants.storages.ThumbnailsStorage(),
                        upload_to=plants.models.thumbnail_path,
                    ),
                ),
                ("plantnet_url", models.URLField(blank=True, null=True)),
                ("gbif_id", models.PositiveIntegerField(blank=True, null=True)),
                ("wikipedia_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_main", models.BooleanField()),
                ("image", models.ImageField(upload_to="plant_images")),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        related_query_name="image",
                        to="plants.Plant",
                    ),
                ),
            ],
        ),
    ]
