# Generated by Django 3.1.5 on 2021-01-09 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import plants.models
import plants.storages


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="This is the image that will be displayed on each plant card. Must be square and preferably 200x200 pixels.",
                null=True,
                storage=plants.storages.ThumbnailsStorage(),
                upload_to=plants.models.thumbnail_path,
            ),
        ),
    ]
