# Generated by Django 3.1.5 on 2021-01-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_auto_20210109_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="name_lat",
            field=models.TextField(
                blank=True, help_text="Name of the plant in latin", null=True
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="name_alt",
            field=models.TextField(
                blank=True,
                help_text="Alternative name or other common names",
                null=True,
            ),
        ),
    ]
